version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: assessly-server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app           
      - /app/node_modules        
    env_file:
      - ./server/.env           
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: assessly-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true             
    tty: true
    restart: always

  judge0-server:
    image: judge0/judge0:1.13.1
    user: root
    volumes:
      - ./judge0/judge0-v1.13.1/judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    restart: always

  judge0-workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    user: root
    volumes:
      - ./judge0/judge0-v1.13.1/judge0.conf:/judge0.conf:ro
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    restart: always

  judge0-db:
    image: postgres:16.2
    env_file: ./judge0/judge0-v1.13.1/judge0.conf
    volumes:
      - judge0_data:/var/lib/postgresql/data/
    restart: always

  judge0-redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: ./judge0/judge0-v1.13.1/judge0.conf
    restart: always

volumes:
  judge0_data:
